### ISSUE TITLE
Remove the included Symfony session storage

### ISSUE THREAD

**Issue by PeeHaa** [Lusitanian/PHPoAuthLib#118]
Do we really need to bundle the Symfony session storage adapter? I fail to see the need to include some 3rd party session storage.

I would like to drop it from the lib (in some later version) when nobody is in front of my house with torches and pitchforks in the next few days.

So if somebody has a problem with this speak now or forever hold your peace.

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
