### ISSUE TITLE
Question/Bug? Using StreamClient vs Curl - Github POST

### ISSUE THREAD

**Issue by thomaswelton** [Lusitanian/PHPoAuthLib#119]
I was trying to use the GitHub API to create a new service hook.
But errors were getting thrown here. Even though my hook was create successfully https://github.com/Lusitanian/PHPoAuthLib/blob/master/src/OAuth/Common/Http/Client/StreamClient.php#L61

I noticed that the StreamClient was used for "backward compatibility" https://github.com/Lusitanian/PHPoAuthLib/blob/master/src/OAuth/ServiceFactory.php#L112
Using the CurlClient I didn't get any errors.

Whats the difference between the two? Is the stream client the legacy version? And should I always use curl?
Or is this a bug with the stream client?

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
