### ISSUE TITLE
Using SymfonySession and OAuth1 does not work.

### ISSUE THREAD

**Issue by cmfcmf** [Lusitanian/PHPoAuthLib#152]
- It works using `Session` as `$storage`.
- It works using `SymfonySession` with OAuth 2

This call fails:

```
 $token = $storage->retrieveAccessToken('Tumblr');
```

=> 'Token not found in session, are you sure you stored it?' (`SymfonySession`, line 36)

This happens because in `hasAccessToken`, the `$tokens[$service] instanceof TokenInterface;` line fails for some reason, when I debug it I see this:
![image](https://f.cloud.github.com/assets/2145092/1606456/4972d7da-543f-11e3-975e-f416e0352bda.png)

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
