### ISSUE TITLE
Requests which don't require session token

### ISSUE THREAD

**Issue by clod986** [Lusitanian/PHPoAuthLib#158]
I'm not good with git, therefore I still can't do it myself.
The method <code>request()</code> requires a <code>Token</code> to be stored in session. As you know not all calls, for example to facebook, require an access token.

Wouldn't it be a good idea to implement a new method which didn't force us to have a token in session? If not, could someone show me a way to make automated calls from my server using this library? At the moment I'm using a simple <code>file_get_contents('https://graph.facebook.com/')</code>, but I would prefer to use the standard <code>$facebookService->request()</code>

Thanks

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
