### ISSUE TITLE
Proper error handling for the stream client

### ISSUE THREAD

**Issue by PeeHaa** [Lusitanian/PHPoAuthLib#166]
The stream client currently eats the response body on http errors which makes it a pretty crappy experience to debug.

My proposal would be to set the stream context to ignore errors and the http status code to check for errors in request. This would be pretty easy to implement by adding `ignore_errors => true`  to the [context `http` directive](https://github.com/Lusitanian/PHPoAuthLib/blob/master/src/OAuth/Common/Http/Client/StreamClient.php#L80) and by adding a check for the response using `$http_response_header`.

The only thing that is holding me back currently is that I don't know for sure whether all services play nice and give back a somewhat meaningful http status code when the shit hits the fan (i.e. not 200 Okily-dokily).

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
