### ISSUE TITLE
Error: no suitable wrapper could be found

### ISSUE THREAD

**Issue by samyb8** [Lusitanian/PHPoAuthLib#171]
Trying the ETSY example, and after adding my secret and key to the init.php, I see the "Login with Etsy" and once I click on it I get this error:

"Fatal error: Uncaught exception 'OAuth\Common\Http\Exception\TokenResponseException' with message 'file_get_contents(http://openapi.etsy.com/v2/oauth/request_token): failed to open stream: no suitable wrapper could be found' in /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/Common/Http/Client/StreamClient.php:70 Stack trace: #0 /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/OAuth1/Service/AbstractService.php(52): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), Array, Array) #1 /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/examples/etsy.php(54): OAuth\OAuth1\Service\AbstractService->requestRequestToken() #2 {main} thrown in /hermes/bosoraweb013/b1151/ipg.tahara/APIs/PHPoAuthLib-master/src/OAuth/Common/Http/Client/StreamClient.php on line 70"

Is this an issue? Am I missing anything?

**Comment by Chris-Kruining** [comment]
I have the same problem, allow_url_fopen is on in my case
