### ISSUE TITLE
400 Bad Request using localhost to get access token

### ISSUE THREAD

**Issue by williamparry** [Lusitanian/PHPoAuthLib#193]
I'm getting a 400 Bad Request when retrieving the access token on localhost. I've set up the redirect uri on the app to be localhost, and used a [proxy](http://stackoverflow.com/questions/1336262/file-get-contents-behind-a-proxy/1336419#1336419) to ensure that the keys are being sent correctly.

Maybe it's something similar to [this](https://github.com/ozgur/python-linkedin/issues/2).

```
Fatal error: Uncaught exception 'OAuth\Common\Http\Exception\TokenResponseException' with message 'file_get_contents(https://www.linkedin.com/uas/oauth2/accessToken):
 failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request ' in /Applications/XAMPP/xamppfiles/htdocs/xxx.com/OAuth/Common/Http/Client/StreamClient.php:71 
Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/xxx.com/OAuth/OAuth2/Service/AbstractService.php(100): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), Array, Array) #1 /Applications/XAMPP/xamppfiles/htdocs/xxx.com/login.php(42): OAuth\OAuth2\Service\AbstractService->requestAccessToken('AQQg87MtOjyTEwL...') 
#2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/xxx.com/OAuth/Common/Http/Client/StreamClient.php on line 71
```

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
