### ISSUE TITLE
[Question] What is a status of branch v1.0?

### ISSUE THREAD

**Issue by wildsurfer** [Lusitanian/PHPoAuthLib#202]
I see that branch v1.0 differs a lot from master branch. Will it be ever merged with master?

**Comment by samwilson** [comment]
Any news on this? :-)

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
