### ISSUE TITLE
Google - Failed on requestAccessToken function (file_get_contents)

### ISSUE THREAD

**Issue by Dlacreme** [Lusitanian/PHPoAuthLib#261]
Hi,

I'm trying to use PHPoAuthLib to login using Google.
Authentication works fine and I'm redirected on my callback url with a token.

Then, when I try to make a request on google's server, I got an error on this :  

``` php
  $oauth->getService()->requestAccessToken($_GET['code']);
```

It looks like file_get_contents failed :  
- lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:70
- file_get_contents(https://accounts.google.com/o/oauth2/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

Did I made a mistake ?

**Comment by logical-and** [comment]
Anyone, can you reproduce this issue on [updated library](https://github.com/logical-and/php-oauth/tree/master/examples)?

**Comment by dercoder** [comment]
I will try it tomorrow and tell you the result

**Comment by tito433** [comment]
Same here.
When facebook redirects with **code=AQAd9XZiY...** I get the following trace:
`
Fatal error: Uncaught exception 'OAuth\Common\Http\Exception\TokenResponseException' with message 'Failed to request resource. HTTP Code: HTTP/1.1 400 Bad Request' in vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:68 


Stack trace: 
#0 vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/AbstractService.php(183): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), NULL, Array, 'GET') 

#1 phpbb/auth/provider/oauth/service/facebook.php(72): OAuth\OAuth2\Service\AbstractService->request('/me') 

#2 phpbb/auth/provider/oauth/oauth.php(217): phpbb\auth\provider\oauth\service\facebook->perform_auth_login() 

#3 phpbb/auth/auth.php(939): phpbb\auth\provider\oauth\oauth->login('', '') 

#4 includes/functions.php(2314): phpbb\auth\auth->login('', '', false, 1, 0) 

#5 ucp.php(84): login in vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php on line 68`

**Comment by tito433** [comment]
After following @logical-and last comment resolves my problem.
My composer.json was missing "and/oauth": "^0.6.0"
After adding it resolves my problem.

**Comment by DanAlexson90** [comment]
@tito433 What is "and/oauth"?

**Comment by tezrik** [comment]
This issue has been  marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.
