### ISSUE TITLE
file_get_contents(https://accounts.google.com/o/oauth2/token): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized 

### ISSUE THREAD

**Issue by joe-liquid** [Lusitanian/PHPoAuthLib#281]
Hi, 

I am getting the message "file_get_contents(https://accounts.google.com/o/oauth2/token): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized" when I request an access token from Google with "$googleService->requestAccessToken($_GET['code']);". Do you know why this would be? Is this a known issue?

Thanks,

**Comment by katzlbt** [comment]
Do you have the SSL stream wrapper active?
http://stackoverflow.com/questions/1975461/how-to-get-file-get-contents-work-with-https

    <?php 
    $w = stream_get_wrappers();
    echo 'openssl: ',  extension_loaded  ('openssl') ? 'yes':'no', "\n";
    echo 'http wrapper: ', in_array('http', $w) ? 'yes':'no', "\n";
    echo 'https wrapper: ', in_array('https', $w) ? 'yes':'no', "\n";

openssl: no
http wrapper: yes
https wrapper: no
