### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by Nicofuma** [Lusitanian/PHPoAuthLib#311]
We (the phpBB group) use this lib but because of the lack of changelog we can't really update it. 
It could be nice to provide one to explain what are the main new features, the BC break and any other usefull information.

Thank you.

**Comment by logical-and** [comment]
Hello @Nicofuma. I will release v0.5 soon, and add changelog there. You look over update library by this [link](https://github.com/logical-and/php-oauth).

**Comment by logical-and** [comment]
@Nicofuma Is list of GH issues good for you? 

Here is [a link](https://github.com/logical-and/php-oauth/milestones?direction=desc&sort=due_date&state=closed)  for versions.

**Comment by Nicofuma** [comment]
A list of GH issues is better than nothing :) even if a full text changelog is always easier and faster to read :)

By the way, you have abandoned this repository in favor of https://github.com/logical-and/php-oauth ?

**Comment by logical-and** [comment]
@Nicofuma I can provide you the changelog, if it will be better for you. It's not a problem for me. :)
No, https://github.com/Lusitanian/PHPoAuthLib is not my repository, but it's seems abandoned. I created new repository, which based on this and another repository with  user data handlers.

API in  https://github.com/logical-and/php-oauth is the same, so you can simple switch library without any pain. But, I recommend you to use new easier API, you can find examples on how to use it in examples directory.

**Comment by Nicofuma** [comment]
okay thanks. I'll have a look (one day...) to update phpBB

**Comment by logical-and** [comment]
@Nicofuma just added it - [changelog.md](https://github.com/logical-and/php-oauth/blob/master/changelog.md)

**Comment by Nicofuma** [comment]
thank you very much
