### ISSUE TITLE
Latest version is 0.1.x-dev?

### ISSUE THREAD

**Issue by darylphuah** [Lusitanian/PHPoAuthLib#330]
In my composer.json I have the package required as "lusitanian/oauth": "~0.3". I was wondering why I couldn't get the latest commits to get Facebook v2 api working and noticed that on packaglst the latest version is tagged 0.1.x-dev

Is this intended or did something fubar somewhere?

**Comment by logical-and** [comment]
Please try [my updated library](https://github.com/logical-and/php-oauth). Currently it's 0.5 beta version, and development still going on.

**Comment by Lusitanian** [comment]
should be fixed
