### ISSUE TITLE
POST Linkedin Request

### ISSUE THREAD

**Issue by fr4ngus** [Lusitanian/PHPoAuthLib#331]
I try to share content with linkedin.
I want to know if the function below, works because when i do this i have Failed request ressource.
The permissions apps are Good and Token correctly stock.

   
 public function shareWithLinkedin(){
        try {
            $parameters = "
<share>
  <comment>Check out the LinkedIn Share API! https://example.com</comment>
</share>";
            $shareLinkedin = OAuth::consumer('Linkedin')
                ->request('/people/~/shares', 'POST',$parameters);
        }catch(\OAuth\Common\Http\Exception\TokenResponseException $e){
            $e->getMessage();

        }

    }

Thx

**Comment by logical-and** [comment]
Please try it out on [my fork](https://github.com/logical-and/php-oauth), I guess your issue was fixed
