### ISSUE TITLE
Multiple accounts per Service / Use a specific account to make the requests

### ISSUE THREAD

**Issue by developmentstudio** [Lusitanian/PHPoAuthLib#338]
At the moment I have a case where I have multiple accounts per service, for example LinkedIn, Facebook, etc.. Where I need the option to select the account by which the request has to be made.

Is this supported in any kind of way in the PHPoAuthLib? Or is there an easy way to extend it with functionality like this? I already took a look at the Service and Storage related classes, but they depend more or less on the interfaces of each other.

Pointers are welcome.

**Comment by developmentstudio** [comment]
The solution described in #313 works for me.

**Comment by logical-and** [comment]
Hello. I guess you can persist your tokens in storage, different from session. Maybe this idea can help you?
