### ISSUE TITLE
In php version 5.6, login to google oauth may fail.

### ISSUE THREAD

**Issue by mirrorgithub** [Lusitanian/PHPoAuthLib#352]
I modify the code in function "generateStreamContext" of file "lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php" to fix this problem.

Add the "ssl" array like following code.

````
    private function generateStreamContext($body, $headers, $method)
    {
        return stream_context_create(
            array(
                'http' => array(
                    'method'           => $method,
                    'header'           => implode("\r\n", array_values($headers)),
                    'content'          => $body,
                    'protocol_version' => '1.1',
                    'user_agent'       => $this->userAgent,
                    'max_redirects'    => $this->maxRedirects,
                    'timeout'          => $this->timeout
                ),
                'ssl' => array(
                    'verify_peer'      => false,
                    'verify_peer_name' => false
                ),
            )
        );
    }
````

**Comment by logical-and** [comment]
I used third-party library to handle http requests in [updated library](https://github.com/logical-and/php-oauth). I will really appreate, if you can try and tell if it's work.

**Comment by mirrorgithub** [comment]
OK, I will try it once I have free time.

**Comment by mirrorgithub** [comment]
Hey, I just finished the test.
Your library can run successfully on php 5.6 : ).

**Comment by logical-and** [comment]
Ok, super. :)
Let me known, if you will occur any issues. ;)

**Comment by Lusitanian** [comment]
not sure why this would be a PHP issue, just make sure you have proper certs installed. bad idea to not verify.
