### ISSUE TITLE
Add scope linkedin service

### ISSUE THREAD

**Issue by fr4ngus** [Lusitanian/PHPoAuthLib#357]
Hello,
I just want to inform you that you can add a new scope for linkedin:
go to : vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Linkedin.php
and add this because Linkedin update his app: 

const SCOPE_W_SHARE             = 'w_share';

Have a good day !

**Comment by logical-and** [comment]
Just added it on [my fork](https://github.com/logical-and/php-oauth). 
Thank you :)
