### ISSUE TITLE
Problems getting started ...

### ISSUE THREAD

**Issue by katzlbt** [Lusitanian/PHPoAuthLib#378]
Started with an example google.php ...
  0. copied it to my own directory
  1. Included Oauth/bootstrap.php (wrong bootstrap.php!!)
  2. Started 2h search why $currentUri (->getAbsoluteUri()) is not defined.
  3. included the correct bootstrap.php this time ...
  4. require_once __DIR__ . 'Oauth/vendor/autoload.php';
  5. Found vendor on .gitignore
  6. 'Oauth/vendor/autoload.php' should be 'Oauth/bootstrap.php' ??
  7. finally a login panel ... but ...
  8. Fatal error: Uncaught exception 'OAuth\Common\Http\Exception\TokenResponseException' with message 'file_get_contents(https://accounts.google.com/o/oauth2/token): failed to open stream: No such file or directory' 

Could you add a README to the examples?
Thanks for pointers.

Found it 'Oauth/vendor/autoload.php' should be 'Oauth/bootstrap.php' this seems to work.
I highly recommend renaming one of the bootstrap.php files to avoid confusion.

**Comment by logical-and** [comment]
Can you reproduce the error on [my fork](https://github.com/logical-and/php-oauth)?

**Comment by logical-and** [comment]
You should bootstrap OAuth lib by src/bootstrap.php
