### ISSUE TITLE
How to get the facebook profile image?

### ISSUE THREAD

**Issue by odera89** [Lusitanian/PHPoAuthLib#386]
I use Laravel5 and i want to get the facebook profile_image?

**Comment by logical-and** [comment]
@odera89 Hi, you can use special method `->getImageUrl()`, or even save image locally by calling `->saveImage('/path/to/save.png')`.

Full call example for image url is `$facebookService->constructExtractor()->getImageUrl()`

Here is [a link](https://github.com/logical-and/php-oauth/blob/master/examples/facebook.php)  for full example.

Let me know if you will have any questions.

**Comment by odera89** [comment]
Thanks
