### ISSUE TITLE
Facebook, using outdated API v.1 calls?

### ISSUE THREAD

**Issue by canfiax** [Lusitanian/PHPoAuthLib#389]
I am seeing this warning on my Facebook developer page:

![image](https://cloud.githubusercontent.com/assets/3786627/7411934/741fd9a2-ef3d-11e4-9c64-12efe9307b8b.png)

![image](https://cloud.githubusercontent.com/assets/3786627/7411926/5d63ef32-ef3d-11e4-85a1-9faab8008562.png)

Could it be true that it is Lusitanian making v1 calls?

**Comment by logical-and** [comment]
Thank you for reporting. We will fix it soon.

**Comment by logical-and** [comment]
Please let us know, if error still happens

**Comment by jenssegers** [comment]
Note; Facebook switched to json since v2.3.
