### ISSUE TITLE
refreshAccessToken Yahoo Oauth1

### ISSUE THREAD

**Issue by dooplenty** [Lusitanian/PHPoAuthLib#398]
I know it's typically the case that OAuth1 doesn't have the notion of refreshing an access token, but in the case of Yahoo they do. See step 5 for this link. 
https://developer.yahoo.com/oauth/guide/oauth-auth-flow.html
The main difference is that you pass the `oauth_session_handle` in the get_token request instead of the `verifier` Currently there isn't a way to perform this but would be great if there was. Perhaps implemented on the individual service i.e. Yahoo instead of in the AbstractService class.

**Comment by Lusitanian** [comment]
closed #399  thank you!
