### ISSUE TITLE
Scope user_posts is missing from the Facebook class

### ISSUE THREAD

**Issue by aoatridge** [Lusitanian/PHPoAuthLib#401]
Scope user_posts is missing in the Facebook class but is valid scope on Facebook API page.
I have seen another issue on this but it was not merged for some reason.
![fbscopes](https://cloud.githubusercontent.com/assets/898955/8120204/8cb610fa-1051-11e5-928a-15783e426921.png)

**Comment by logical-and** [comment]
Just added it.

**Comment by landons** [comment]
@logical-and, I'm a little confused.  Has your fix been merged into Lusitanian/PHPoAuthLib?  Or just in your php-oauth library?

**Comment by logical-and** [comment]
PHPoAuthLib is abandoned library, so I merged it in php-oauth library.

**Comment by landons** [comment]
Gotcha.  It looks like you made some major changes to the library, so I opted for forking it instead.  Thanks for the quick reply.

**Comment by Lusitanian** [comment]
Done!
