### ISSUE TITLE
How to make OAuth calls with Access Token and Secret

### ISSUE THREAD

**Issue by dskanth** [Lusitanian/PHPoAuthLib#459]
Hi, i am using this PHP Library to authenticate the user and fetch his Access Token and Access Token Secret. I am storing them in a config file.
Now, i would like to make authenticated OAuth calls on behalf of user, having his token values in the config file. How can i build an Authorization header manually and make OAuth requests ?

Please let me know. Refer Stackoverflow question [here](http://stackoverflow.com/questions/35311615/make-oauth-api-calls-with-access-token-and-access-token-secret).

**Comment by elliotchance** [comment]
What service is this against?

**Comment by dskanth** [comment]
This is for a service (confidential), which has implemented OAuth 1.0, very similar to Twitter. I have figured out a solution to it, which i answered here: https://github.com/Lusitanian/PHPoAuthLib/issues/96#issuecomment-183222141

**Comment by 9916boarder** [comment]
What does this do exactly?

**Comment by dskanth** [comment]
I wanted to make OAuth calls on behalf of a user, once i have the values of his OAuth Access Token and OAuth Access Token Secret. I am able to achieve it by storing those values in a Session.

**Comment by 9916boarder** [comment]
So is this a way for certain phone numbers can call or be called without record of it?

**Comment by dskanth** [comment]
@9916boarder, I am not sure what you are asking.
