### ISSUE TITLE
Post request to gmail api using oriceon/oauth-5-laravel

### ISSUE THREAD

**Issue by dukeForsyth** [Lusitanian/PHPoAuthLib#505]
Hello I am not sure this is the right place to post this question so do say if I am out of place but I am trying to send an email via an authorized users account in my web project. I am currently using **Laravel 5.2 and  oriceon/oauth-5-laravel wrapper** so that I can use this package still.
I am pretty sure I have the correct scopes and I can get emails and such correctly but when trying to post to send an email for an authorized user I run into issues 
**The issue is I keep getting:
TokenResponseException in StreamClient.php line 68:
Failed to request resource. HTTP Code: HTTP/1.1 400 Bad Request**

Below is my attempt currently and I am not sure what I could be messing up. note emails are just silly examples not what I am using currently.

            $token = $googleService->requestAccessToken($code);
            $message = Swift_Message::newInstance();
            $message->setSubject("Test Email");
            $message->setTo("testemail@gmail.com");
            $message->setReplyTo("tester@gmail.com");
            $message->setBody("This is a test of adding a body!");
            $data_to_send = $this->base64url_encode($message->toString());
            $arr = array('raw'=>$data_to_send);
            $json = json_encode($arr);
            $result = $googleService->request('https://www.googleapis.com/gmail/v1/users/me/messages/send','POST', $json, array())););

using the encoded information from above on googles "try this" example on their API page [https://developers.google.com/gmail/api/v1/reference/users/messages/send] I see that the encoded email sends correctly with there version so I feel like I am just doing something silly.

Any help would be appreciated!

**Comment by dukeForsyth** [comment]
Figured my issue out and forgot to close this issue sorry!

**Comment by ruslanashaari** [comment]
please, how do you solve it?

**Comment by dukeForsyth** [comment]
Sorry what is the problem that you are facing with the API?

**Comment by ruslanashaari** [comment]
TokenResponseException in StreamClient.php line 68:
Failed to request resource. HTTP Code: HTTP/1.1 400 Bad Request

Received this error after user select gmail account. Is this error on redirect_uri? I'm using laravel 5.1 btw

**Comment by dukeForsyth** [comment]
For the bad requests you have to make sure that you're sending the
information like they ask in the Gmail API.

You also have to make sure that the URL that you provided for Google
matches exactly what your return address will be.

Aside from that I believe if you have the code similar to mine it should
work.

Also I was running 5.2 so not sure if there is a difference there or not.
