### ISSUE TITLE
 getAbsoluteUri

### ISSUE THREAD

**Issue by audas** [Lusitanian/PHPoAuthLib#515]
Sorry I'm missing something here - but keep getting this fatal error

> PHP Fatal error:  Call to a member function getAbsoluteUri() on null 

coming from the credentials initialisation.

```
$credentials = new Credentials(
    $servicesCredentials['vimeo']['key'],
    $servicesCredentials['vimeo']['secret'],
    $currentUri->getAbsoluteUri()
);
```

**Comment by prasitnarkdee** [comment]
maybe this help, I try to config with google

use OAuth\ServiceFactory;
use OAuth\Common\Http\Uri\Uri;

$currentUri     = new Uri('http://domain.com/login.php');
$serviceFactory = new ServiceFactory();

**Comment by absmendoza** [comment]
I just stumbled upon this package now and currently fiddly with it, but where do I set up my credentials such the client_id, client_secret and redirect/callback url? I'm having a hard time looking for it.

**Comment by prasitnarkdee** [comment]
@absmendoza please follow https://github.com/Lusitanian/PHPoAuthLib/issues/517
