### ISSUE TITLE
Steam (Login with Steam)

### ISSUE THREAD

**Issue by Burnett01** [Lusitanian/PHPoAuthLib#68]
It would be nice to use Steam 

https://developer.valvesoftware.com/wiki/Steam_Web_API

Regards,

Steve

**Comment by Jonhasacat** [comment]
Steam now supports OAuth (has for some time IIRC). https://steamcommunity.com/dev

I'm tempted to add support myself, but I'm a bit intimidated by how huge some of the files are (looking at Facebook).

I'll submit a pull request if I get it working, but if you get it done in the meantime that would be sweet.

**Comment by Burnett01** [comment]
Sorry for me late reply ( almost 4 years), but you are right. Steam doesn't use OAuth. It is OpenID, thus out of scope, as you stated correctly. Thanks man.
