### ISSUE TITLE
Request with Stored Token

### ISSUE THREAD

**Issue by oblogic7** [Lusitanian/PHPoAuthLib#96]
I think I am missing something, but can't quite figure it out.  I can successfully request and store an OAuth1 access token and token secret. However, I cannot figure out what I am missing when trying to make a request with the stored token.

Here is my code...

``` php
      // Fetch stored access token.
      $stored_token = Token::getUserToken($service);

      $token = new StdOAuth1Token();
      $token->setAccessToken($stored_token->token);
      $token->setAccessTokenSecret($stored_token->token_secret);

      // Initialize OAuth consumer (hannesvdvreken/laravel-oauth)
      $consumer = OAuth::consumer($service);
      $consumer->getStorage()->storeAccessToken($service, $token);

      $consumer->request('API_URL_HERE');
```

The request returns "Failed to request resource".  I know I have to be missing something obvious, but I am unsure what since this is my first time to implement OAuth.

**Comment by dskanth** [comment]
I have slightly tweaked the functionality of fetching token from storage. I am fetching token from a config php file, after i store the token in it. The token can also be stored in a local PHP session and read from it.

The code  for storing token is in Service/AbstractService.php:
$this->storage->storeAccessToken($this->service(), $token);

You can modify it like the following, to store the token in a session variable:
$_SESSION['access_token'] = serialize($token);

Then when making a request to API, you can modify the code in request() function to use token from session:

Change: $token = $this->storage->retrieveAccessToken($this->service());
To: $token = unserialize($_SESSION['access_token']);

This way, i could use custom PHP sessions to store and retrieve access tokens. You can also use Database or a text file to store and retrieve the tokens. It works!
